name: Scrape Timetables Daily

on:
  workflow_dispatch:      # allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * *'   # every day at midnight (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug:Print environment variables
        run: printenv

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Debug:Print Node.js and npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Debug:List installed dependencies
        run: ls -la node_modules

      - name: Run scraper
        run: node list-classes.js

      - name: Debug:List all workspace files post‑scrape
        run: ls -R .

      - name: Debug:Show sample of classes.json
        run: head -n 50 classes.json

      - name: Debug:Count timetable entries
        run: |
          node -e "const fs=require('fs'); const data=JSON.parse(fs.readFileSync('classes.json')); console.log('Entries:', Array.isArray(data) ? data.length : Object.keys(data).length);"

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON
        uses: actions/download-artifact@v3
        with:
          name: timetable-json
          path: ./downloaded

      - name: Debug:List downloaded files
        run: ls -la downloaded

      - name: Debug:Show downloaded timetable
        run: cat downloaded/classes.json
