name: Scrape timetables daily

# Run at 00:05 UTC every day
on:
  schedule:
    - cron:  '5 0 * * *'
  workflow_dispatch:  # allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      VA_USER: ${{ secrets.VA_USER }}
      VA_PASS: ${{ secrets.VA_PASS }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Scrape timetable JSON
        run: |
          node list-classes.js > classes.json

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json
