name: Scrape Timetables Daily

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps
        run: npm ci

      - name: Scrape classes
        run: node list-classes.js

      - name: Upload JSON
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json

      - name: Download JSON
        uses: actions/download-artifact@v3
        with:
          name: timetable-json
          path: downloaded/
