name: Scrape Timetables Daily

on:
  workflow_dispatch:      # manual trigger via GitHub UI
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      VA_USER: ${{ secrets.VA_USER }}
      VA_PASS: ${{ secrets.VA_PASS }}
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium-browser'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Confirm Chromium binary
        run: |
          which chromium-browser || which chromium
          chromium-browser --version

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --verbose

      - name: Run scraper (capture to classes.json)
        run: node list-classes.js > classes.json

      - name: Debug:Show classes.json
        run: |
          ls -la classes.json
          head -n 20 classes.json

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json

  publish:
    needs: scrape
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download timetable JSON
        uses: actions/download-artifact@v4
        with:
          name: timetable-json
          path: .

      - name: Copy JSON into docs
        run: |
          mkdir -p docs
          cp classes.json docs/classes.json

      - name: Commit & Push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/classes.json
          git commit -m "Publish timetable for $(date -I --utc)"
          git push
