name: Scrape Timetables Daily

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node list-classes.js

      - name: Debug:List workspace files
        run: ls -la

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json

  publish:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download timetable JSON
        uses: actions/download-artifact@v3
        with:
          name: timetable-json
          path: .

      - name: Copy JSON into docs
        run: |
          mkdir -p docs
          mv classes.json docs/classes.json

      - name: Commit & Push to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/classes.json
          git commit -m "Publish timetable JSON for $(date -I)"
          git push
