name: Scrape Timetables Daily

on:
  workflow_dispatch:      # allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * *'   # every day at midnight (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug:Print environment variables
        run: printenv

      - name: Debug:Print Node.js, npm versions and npm config
        run: |
          echo '--- Node & npm versions ---'
          node -v
          npm -v
          echo '--- NPM config ---'
          npm config list

      - name: Debug:Show .npmrc (if any)
        run: cat ~/.npmrc || echo '(no .npmrc)'

      - name: Debug:Show package.json
        run: |
          echo '--- package.json ---'
          cat package.json

      - name: Debug:Show top of package-lock.json
        run: |
          echo '--- head package-lock.json ---'
          head -n 50 package-lock.json

      - name: Install dependencies (with verbose logging)
        run: npm ci --verbose
        continue-on-error: true

      - name: Debug:List NPM debug logs
        run: |
          echo '--- NPM log directory ---'
          ls -lah /home/runner/.npm/_logs
          echo '--- NPM logs ---'
          cat /home/runner/.npm/_logs/*.log || echo '(no logs found)'

      - name: Debug:Check for puppeteer in dependencies
        run: |
          node -e "const pkg=require('./package.json'); \
          console.log('puppeteer declared in dependencies:', \
            !!(pkg.dependencies && pkg.dependencies.puppeteer));"

      - name: Run scraper
        if: ${{ success() }}
        run: node list-classes.js

      - name: Debug:List all workspace files post‑scrape
        if: ${{ success() }}
        run: ls -R .

      - name: Upload timetable JSON
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON
        if: ${{ success() }}
        uses: actions/download-artifact@v4
        with:
          name: timetable-json
          path: ./downloaded

      - name: Debug:List downloaded files
        if: ${{ success() }}
        run: ls -la downloaded

      - name: Debug:Show downloaded timetable
        if: ${{ success() }}
        run: cat downloaded/classes.json
