name: Scrape Timetables Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight
  workflow_dispatch:    # Allows you to trigger it manually from the Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper
        run: node list-classes.js

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v3.1.2
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON (for further use)
        uses: actions/download-artifact@v3.1.2
        with:
          name: timetable-json
          path: downloaded/
