name: Scrape Timetables Daily

on:
  workflow_dispatch:      # allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * *'   # every day at midnight (UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # Skip Puppeteer’s Chromium download
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      # (Puppeteer’s default macOS path will be symlinked to this)
      PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug:Confirm system Chromium
        run: |
          which chromium-browser || which chromium
          chromium-browser --version || chromium --version

      - name: Create macOS‑style Chrome path
        run: |
          sudo mkdir -p "/Applications/Google Chrome.app/Contents/MacOS"
          sudo ln -sf /usr/bin/chromium-browser "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Debug:Print Node & npm versions
        run: |
          node -v
          npm -v

      - name: Show package.json & lockfile head
        run: |
          echo '--- package.json ---'
          cat package.json
          echo '--- head package-lock.json ---'
          head -n 30 package-lock.json

      - name: Install dependencies
        run: npm ci --verbose

      - name: Debug:Verify Puppeteer installation
        run: |
          npm ls puppeteer
          ls -la node_modules/puppeteer

      - name: Run scraper
        run: node list-classes.js

      - name: Debug:List workspace files post‑scrape
        run: ls -R .

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v4
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON
        uses: actions/download-artifact@v4
        with:
          name: timetable-json
          path: ./downloaded

      - name: Debug:Show downloaded timetable
        run: cat downloaded/classes.json
