name: Scrape Timetables Daily

on:
  schedule:
    - cron: '0 0 * * *'     # Every night at midnight UTC
  workflow_dispatch:       # Allows manual runs in the UI

permissions:
  contents: read
  actions: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Scrape classes
        run: node list-classes.js

      

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v3
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON (for downstream jobs)
        uses: actions/download-artifact@v3
        with:
          name: timetable-json
          path: downloaded/
