name: Scrape Timetables Daily

on:
  workflow_dispatch:      # manual trigger via GitHub UI
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      VA_USER: ${{ secrets.VA_USER }}
      VA_PASS: ${{ secrets.VA_PASS }}
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      PUPPETEER_EXECUTABLE_PATH: '/usr/bin/chromium-browser'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Confirm Chromium binary
        run: |
          which chromium-browser || which chromium
          chromium-browser --version

      - name: Set up Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci --verbose

      - name: Run scraper (capture to classes.json)
        run: node list-classes.js > classes.json

      - name: Debug:Show the new classes.json
        run: |
          ls -la classes.json
          head -n 20 classes.json

      - name: Upload timetable JSON
        uses: actions/upload-artifact@v4
        with:
          name: timetable-json
          path: classes.json

      - name: Download timetable JSON
        uses: actions/download-artifact@v4
        with:
          name: timetable-json
          path: ./downloaded

      - name: Debug:Show downloaded timetable
        run: cat downloaded/classes.json
